language: php

php:
  - 5.6
  - 7.0
  - hhvm

addons:
  code_climate:
    repo_token: 534dd28884bb7ecbc45055cd430e4dafbe7e69e4e0efad1875e452596d01f483

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ] && [ $TRAVIS_PHP_VERSION != "7.0" ] && [ $TRAVIS_PHP_VERSION != "nightly" ];  then vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text; else vendor/bin/phpunit; fi

after_script:
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ] && [ $TRAVIS_PHP_VERSION != "7.0" ] && [ $TRAVIS_PHP_VERSION != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ] && [ $TRAVIS_PHP_VERSION != "7.0" ] && [ $TRAVIS_PHP_VERSION != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi


